# -*- coding: utf-8 -*-
"""problem_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niigchSE9_Nw_r_-4-BytqRvT6c59A0S
"""

# Leet Code Problem 1.

def twoSum(self,nums, target):

    position = []
    end = False

    for i in range(0,len(nums)-1):
        num_1 = nums[i]
        #print(num_1)
        for j in range(i+1, len(nums)):
            num_2 = nums[j]
            #print(num_2)
            #print(num_1 + num_2)

            if num_1 + num_2 == target:

                position.append(i)
                position.append(j)
                end = True
                break

        if end == True:

            break

    return position

print(lengthOfLongestSubstring2('pwwkew'))



len('c')

len(s)

